version: '3.7'

services:
  postgres:
    image: postgres:14-alpine
    hostname: postgres
    networks:
      - core-infra
    ports:
      - "5432:5432"
    volumes:
      - postgis-data:/var/lib/postgresql
      - dbbackups:/backups
    environment:
      - "TZ=${DEFAULT_TIMEZONE}"
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    networks:
      - core-infra
      - core-pub
    ports:
      - "${PG_ADMIN_PORT}:80"
    hostname: pgadmin
    volumes:
      - pgadmin:/var/lib/pgadmin
    environment:
      - "TZ=${DEFAULT_TIMEZONE}"
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    restart: always
    depends_on:
      - postgres

networks:
  core-infra:
    external: true
  core-pub:
    external: true

volumes:
  pgadmin:
  dbbackups:
  postgis-data:
